### ISSUE TITLE
Need a better Couch package

### ISSUE THREAD

**Issue by mmalecki** [spacedock-io/docker-index#19]
This one doesn't even pass in the error code in a readable way.

I can start working on it in the morning, so if someone can take it earlier, please do so.

**Comment by Southern** [comment]
That's... about the best one we could find, to be honest. They're all pretty much shit.

**Comment by yawnt** [comment]
http://godoc.org/github.com/dustin/go-couch

**Comment by yawnt** [comment]
at least this one returns errors in a decent fashion

**Comment by Southern** [comment]
Are we satisfied with the one we have now?

**Comment by Southern** [comment]
NEVAMIND! WE'Z ON POSTGRES NOW!
