### ISSUE TITLE
When a user adds an email, we don't check if it's a duplicate

### ISSUE THREAD

**Issue by mmalecki** [spacedock-io/docker-index#24]
#6

**Comment by AvianFlu** [comment]
This can now be solved easily by a unique constraint on the `email` field in the DB.  Thoughts?

**Comment by Southern** [comment]
Sounds good to me.

**Comment by yawnt** [comment]
ditto

**Comment by AvianFlu** [comment]
The only thing here is, do we want to allow the same email to be tied to more than one account?

I can't really think of why, but we should make sure before we add the unique constraint.

**Comment by yawnt** [comment]
that might only be the case if we have like, one Spacedock User registering to more registries as a Registry user with the same mail.. i guess the sane thing here it to have a multi-multi relationship between users and registries so we need only to store data once?

**Comment by AvianFlu** [comment]
If this becomes important, we can just have people do the username+tag@email.com crap until we figure it out.  This just isn't important right now, and I added the unique key constraint already.
