### ISSUE TITLE
Persistent database

### ISSUE THREAD

**Issue by Southern** [spacedock-io/docker-index#3]
So, I know that we agreed on using redis for the database. However... looking at the persistent options that redis has, shouldn't we use something else for our user database?

RDB is recommended to run at 5 minute intervals, which means images and such would be lost within that 5 minutes.

AOF is just a log of commands to run when the server starts up to restore the dataset, but that seems like it would make the server restarts extremely long when we have a huge dataset.

We need to have something that is persistent by nature, just in case there is some kind of power outage at a data center where we're running servers at. What would you guys like to use? @yawnt mentioned before that there wasn't really a good CouchDB package for Go, and there really isn't. We could use MongoDB. There is an extremely detailed MongoDB driver called [mango](http://godoc.org/labix.org/v2/mgo).

/cc @yawnt @mmalecki

**Comment by yawnt** [comment]
redis is persistent by default

**Comment by yawnt** [comment]
anyway imma read the persistency page and see what's up

**Comment by yawnt** [comment]
uhm okay, i honestly think a mixing AOF + RDB is pretty okay .. we don't store big datas in redis, just strings.. so it shouldn't be _that_ slow to bootup .. @mmalecki ?

**Comment by yawnt** [comment]
sorry, closed by accident XD

**Comment by mmalecki** [comment]
The problem I have with Redis is [this](http://aphyr.com/posts/283-call-me-maybe-redis). Redis Sentinel is not secure enough in terms of data loss to use as a database.

What do you guys think about http://code.google.com/p/couch-go/?

**Comment by yawnt** [comment]
wasn't updated in almost two years.. the only one i know of that isn't abandoned is https://github.com/couchbaselabs/go-couchbase but i'm not sure how compatible it is with vanilla CouchDB

**Comment by mmalecki** [comment]
Right. We'd probably need something with support for update handlers and views, something like `nano` for Go perhaps.

@yawnt how hard would it be to write a driver like that?

**Comment by yawnt** [comment]
not hard but not worth it.. we need to throw our something that works.. key value storage is enough for now

**Comment by yawnt** [comment]
throw out

**Comment by mmalecki** [comment]
Okay, let's do Redis then.
I'm not really comfortable with using it as a long-term database tho, so let's build the models so that we can switch to a different database easily.

**Comment by yawnt** [comment]
no, i'm saying that we can use go-couch too,but just as an intermediate step.. we just use save and get and not views, etc.. we can build one later
