### ISSUE TITLE
SQLi

### ISSUE THREAD

**Issue by Southern** [spacedock-io/docker-index#32]
We need to work on preventing SQL injections. I was just testing the token stuff, because I forgot about parsing quotations in the code. However, right now it functions with or without the quotations because it's passing it directly into the SQL statement.

Obviously this isn't a huge deal during the MVP, as I doubt people are going to try to break things.

**Comment by yawnt** [comment]
why are we using SQL statements when we should search using a struct and have Gorm build the query?

**Comment by mmalecki** [comment]
I think this can be closed since we're using Gorm to prepare our queries, right?

**Comment by yawnt** [comment]
i _think_ so

**Comment by Southern** [comment]
I'm going to do some SQLi testing today to see if we have anything to worry about.

**Comment by yawnt** [comment]
don't, it's just taking time away from MVP .. if we use the ORM in the right way let's just put faith in that.. we can pen test it later

**Comment by Southern** [comment]
Alright. This is assigned to production anyway, so I'll get the testing done before then.

**Comment by AvianFlu** [comment]
It's fine, nobody is actually writing raw queries. I'm closing this.
