### ISSUE TITLE
Access levels

### ISSUE THREAD

**Issue by Southern** [spacedock-io/docker-index#33]
So, we need to figure out how we want to store access levels.

Do we want to just make a middleware that we can put in front of the routes that require these levels? Something like... `common.RWAccess`, `common.ReadAccess`, `common.DeleteAccess`?

Access will be stored in the `models.User` struct so that we can just look at what a user has access to, rather than querying the database for all of the access levels associated with a repository.

**Comment by mmalecki** [comment]
+1 for middleware (unless it limits us in any way).
